services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flexcity
      MYSQL_USER: flexcity
      MYSQL_PASSWORD: flexcity
    ports:
      - "3306:3306"
    volumes:
      - flexcity_data:/var/lib/mysql

volumes:
  flexcity_data:
